rundeck:
  build: .
  ports:
    - 4440:4440
  links:
    - mysql:mysql
  environment:
    RDECK_HOST: "192.168.99.100"
    DATABASE_URL: "jdbc:mysql://mysql/rundeck?autoReconnect=true"
    DATABASE_USER: rundeck
    DATABASE_PASSWORD: rundeck
  volumes:
    - ./plugins-source:/build

mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: rundeck
    MYSQL_USER: rundeck
    MYSQL_PASSWORD: rundeck
