rundeck:
  image: kallqvist/rundeck-rancher
  ports:
    - 4440:4440
  links:
    - mysql:mysql
  environment:
    RDECK_HOST: "127.0.0.1"
    CATTLE_CONFIG_URL: "https://rancher.example.com/v1"
    CATTLE_ACCESS_KEY: "xyz123"
    CATTLE_SECRET_KEY: "xyz123"
    RDECK_ADMIN_USERNAME: admin
    RDECK_ADMIN_PASSWORD: admin
    DATABASE_URL: "jdbc:mysql://mysql/rundeck?autoReconnect=true"
    DATABASE_USER: rundeck
    DATABASE_PASSWORD: rundeck
  volumes:
    - ./rundeck-logs:/var/lib/rundeck/logs

mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: rundeck
    MYSQL_USER: rundeck
    MYSQL_PASSWORD: rundeck
