# yaml plugin metadata

name: rancher-plugin
version: 1.0
rundeckPluginVersion: 1.2
author: Damien MURE - ATIH
date: 2017-03-20
providers:
    - name: rancher-resources
      title: Rancher container resource collector
      service: ResourceModelSource
      resource-format: resourcejson
      plugin-type: script
      script-interpreter: python
      script-file: container_resource_model.py
      config:
        - type: String
          name: cattle_config_url
          title: Rancher API URL.
          description: "Url the reach rancher API (ex: https://myrancher.me/v1)"
          required: true
        - type: String
          name: cattle_access_key
          title: Rancher acces key
          description: API key needed to connect to Rancher API
          required: true
        - type: String
          name: cattle_secret_key
          title: Rancher secret key
          description: Secret key associated to the acces key
          required: true
        - type: String
          name: environments_ids
          title: Environment ID
          description: Enter the Rancher environment ID to use for filtering
          required: true
        - type: String
          name: stack_filter
          title: Stack filter
          description: Enter the Rancher stack name regex pattern to use for filtering (optional)
        - type: Boolean
          name: limit_one_container
          title: Limit to one container per service
          description: Enable to return only one container per service
          required: true
          default: true
    - name: rancher-executor
      title: Rancher container script executor
      service: NodeExecutor
      plugin-type: script
      script-interpreter: python
      script-file: container_node_executor.py
      config:
        - type: String
          name: cattle_access_key
          title: Rancher acces key
          description: API key needed to connect to Rancher API
          required: true
        - type: String
          name: cattle_secret_key
          title: Rancher secret key
          description: Secret key associated to the acces key
          required: true
        - type: String
          name: cattle_config_url
          title: Rancher API URL.
          description: "Url the reach rancher API (ex: https://myrancher.me/v1)"
          required: true
    - name: rancher-filecopy
      title: Rancher container file copier
      service: FileCopier
      plugin-type: script
      script-interpreter: python
      script-file: container_copy_file.py
      script-args: 1 2 3 # todo: remove
    - name: rancher-trigger-runonce
      title: Trigger Rancher run-once container
      service: WorkflowNodeStep
      plugin-type: script
      script-interpreter: python
      script-file: container_runonce.py
