# yaml plugin metadata

name: python-plugin
version: 0.1
rundeckPluginVersion: 1.2
author: kallqvist
date: 2016-11-11
providers:
    - name: envtest-resources
      service: ResourceModelSource
      resource-format: resourcejson
      plugin-type: script
      script-interpreter: python
      script-file: resource-model.py
    - name: envtest-executor
      service: NodeExecutor
      mergeEnvironment: true
      plugin-type: script
      script-interpreter: python
      script-file: node-executor.py
    - name: envtest-filecopy
      service: FileCopier
      plugin-type: script
      script-interpreter: python
      script-file: copy-file.py
      script-args: 1 2 3 # not supposed to be required?
