# yaml plugin metadata

name: rancher-plugin
version: 0.1
rundeckPluginVersion: 1.2
author: Klas Källqvist
date: 2016-11-11
providers:
    - name: rancher-resources
      service: ResourceModelSource
      resource-format: resourcejson
      plugin-type: script
      script-interpreter: python
      script-file: resource-model.py
      config:
        - type: String
          name: stack_name
          title: Stack name
          description: Enter the Rancher stack name to use for filtering (optional)
    - name: rancher-executor
      service: NodeExecutor
      mergeEnvironment: true
      plugin-type: script
      script-interpreter: python
      script-file: node-executor.py
    - name: rancher-filecopy
      service: FileCopier
      plugin-type: script
      script-interpreter: python
      script-file: copy-file.py
      script-args: 1 2 3
    - name: rancher-nodestep
      service: WorkflowNodeStep
      plugin-type: script
      script-interpreter: python
      script-file: runonce.py
