# yaml plugin metadata

name: rancher-plugin
version: 0.1
rundeckPluginVersion: 1.2
author: Klas Källqvist
date: 2016-11-11
providers:
    - name: rancher-resources
      title: Rancher container resource collector
      service: ResourceModelSource
      resource-format: resourcejson
      plugin-type: script
      script-interpreter: python
      script-file: container-resource-model.py
      config:
        - type: String
          name: environment_id
          title: Environment ID
          description: Enter the Rancher environment ID to use for filtering
          required: true
        - type: String
          name: stack_filter
          title: Stack filter
          description: Enter the Rancher stack name regex pattern to use for filtering (optional)
        - type: Boolean
          name: limit_one_container
          title: Limit to one container per service
          description: Enable to return only one container per service
          required: true
          default: true
    - name: rancher-executor
      title: Rancher container script executor
      service: NodeExecutor
      mergeEnvironment: true
      plugin-type: script
      script-interpreter: python
      script-file: container-node-executor.py
    - name: rancher-filecopy
      title: Rancher container file copier
      service: FileCopier
      plugin-type: script
      script-interpreter: python
      script-file: container-copy-file.py
      script-args: 1 2 3 # todo: remove
    - name: rancher-trigger-runonce
      title: Trigger Rancher run-once container
      service: WorkflowNodeStep
      plugin-type: script
      script-interpreter: python
      script-file: container-runonce.py
