# yaml plugin metadata

name: docker-plugin
version: plugin version
rundeckPluginVersion: 1.0
author: author name
date: release date
providers:
    - name: docker-resources
      service: ResourceModelSource
      resource-format: resourcejson
      plugin-type: script
      script-interpreter: python
      script-file: hello.py
      script-args: a b c
    - name: docker-executor
      service: NodeExecutor
      plugin-type: script
      script-interpreter: python
      script-file: hello.py
      script-args: d e f
    - name: docker-filecopy
      service: FileCopier
      plugin-type: script
      script-interpreter: python
      script-file: hello.py
      script-args: g h i
